# Generated by Django 4.2.9 on 2024-01-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=100)),
                ('total_volume', models.DecimalField(decimal_places=10, max_digits=20)),
                ('profit_rate', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
