# Generated by Django 4.2.9 on 2024-01-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessKey', models.CharField(max_length=200)),
                ('secretKey', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=10)),
                ('time_sleep', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TradeBot',
            new_name='TradeBotCommand',
        ),
        migrations.RenameModel(
            old_name='TradeBotLog',
            new_name='TradeBotLogCommand',
        ),
        migrations.CreateModel(
            name='TradeBotCommandDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profit_rate', models.FloatField()),
                ('transaction_volume_rate', models.FloatField()),
                ('trade_price', models.FloatField()),
                ('trade_volume', models.FloatField()),
                ('compare_data_count', models.CharField(max_length=100)),
                ('rolling_data_count', models.CharField(max_length=100)),
                ('ask_bid', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeapi.tradebotcommand')),
            ],
        ),
        migrations.AlterField(
            model_name='tradebotlogcommand',
            name='trade_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeapi.tradebotcommanddetail'),
        ),
    ]
