# Generated by Django 4.2.9 on 2024-01-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapi', '0002_tradebotsetting_rename_tradebot_tradebotcommand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBotLogCommand1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
                ('is_error', models.BooleanField(default=False)),
                ('trade_market', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TradeBotLogCommand',
        ),
    ]
