# Generated by Django 4.2.9 on 2024-01-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapi', '0003_tradebotlogcommand1_delete_tradebotlogcommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBuyBotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trade_price', models.FloatField()),
                ('trade_volume', models.FloatField()),
                ('ask_bid', models.CharField(max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
