# Generated by Django 4.2.9 on 2024-01-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapi', '0005_tradecoin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradeCoin',
            new_name='TradeCrypto',
        ),
    ]
